### ISSUE TITLE
How to require two keys be combined

### ISSUE THREAD

**Issue by ghost** [ippa/chingu#41]
For example, on a Mac command + q is common for quitting. How can I bind this to :exit?

Thanks

**Comment by ippa** [comment]
You'll have to go with  if holding_all?(key1, key2) { exit } in the game loop

**Comment by ghost** [comment]
I can't seem to get that to work. Do you have an example somewhere?

Thanks.

**Comment by ippa** [comment]
This works fine for me on win9/ruby 1.9.2:

  if holding_all?(:a, :left_ctrl)
    exit
  end

**Comment by ippa** [comment]
not sure about the mac command key though. As you can see here ( http://rubydoc.info/github/ippa/chingu/master/Chingu/Input ) Chingu tries to map all GOSUs keyboard constant to easy-to-remember-ruby-symbols. 

Since I don't use mac I'm not sure what constant is triggered with the mac command key. My guess would be ctrl .. but then the above code should work. I've shot a question to jlnr (GOSU author) on #gosu @ freenode, we'll see what answer I get :). You can also find me there if you wanna chat.

**Comment by ippa** [comment]
After talking to Julian on #gosu, I think this is what you should use:
:left_meta
:right_meta

**Comment by ippa** [comment]
so, holding_all?(:a, :left_meta) for your case maybe

**Comment by ghost** [comment]
Yup. Works like a charm. Thanks! 

On 13.12.2011 16:06, ippa wrote:

> so, holding_all?(:a, :left_meta) for your case maybe
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/ippa/chingu/issues/41#issuecomment-3131242 [1]

## Links:

[1]
https://github.com/ippa/chingu/issues/41#issuecomment-3131242
